version: "3.9"

services:
  mysql:
    container_name: 'mysql'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "LeetCode"
    # restart: always
    ports:
      - "35000:3306"
#    volumes:
#      - '${PWD}/data/db:/var/lib/mysql'