version: "3.7"

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "6000:5432"
#    volumes:
#      - '${PWD}/data/db:/var/lib/postgresql/data'